/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["listProjects"];
        put?: never;
        /** Create Project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/system/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hardware
         * @description Hardware disponible y dispositivo recomendado (RF-TRN-01).
         */
        get: operations["getHardware"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CPUInfo */
        CPUInfo: {
            /** Arch */
            arch: string;
            /**
             * Flags
             * @description Instrucciones relevantes (avx2, avx512…)
             */
            flags?: string[];
            /** Logical Cores */
            logical_cores: number;
            /** Model */
            model: string;
            /** Physical Cores */
            physical_cores: number | null;
        };
        /**
         * Device
         * @enum {string}
         */
        Device: "cuda" | "rocm" | "xpu" | "cpu";
        /** GPUInfo */
        GPUInfo: {
            backend: components["schemas"]["Device"];
            /** Compute Capability */
            compute_capability?: string | null;
            /** Driver */
            driver?: string | null;
            /** Index */
            index: number;
            /** Name */
            name: string;
            /**
             * Supports Bf16
             * @default false
             */
            supports_bf16: boolean;
            /** Vram Free Gb */
            vram_free_gb?: number | null;
            /** Vram Total Gb */
            vram_total_gb: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareReport */
        HardwareReport: {
            cpu: components["schemas"]["CPUInfo"];
            /** Disk Free Gb */
            disk_free_gb: number;
            /** Gpus */
            gpus?: components["schemas"]["GPUInfo"][];
            /** Notes */
            notes?: string[];
            /** Os */
            os: string;
            /** Python */
            python: string;
            /** Ram Available Gb */
            ram_available_gb: number;
            /** Ram Total Gb */
            ram_total_gb: number;
            recommended_device: components["schemas"]["Device"];
            /** Recommended Torch Variant */
            recommended_torch_variant: string;
            torch: components["schemas"]["TorchInfo"];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * Modality
         * @enum {string}
         */
        Modality: "tabular" | "image" | "text" | "timeseries" | "audio";
        /**
         * PrivacyLevel
         * @description Qué puede recibir el LLM (SPEC §7.7.3).
         * @enum {string}
         */
        PrivacyLevel: "L0" | "L1" | "L2" | "L3";
        /** Project */
        Project: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Goal
             * @description Objetivo en lenguaje natural del usuario
             * @default
             */
            goal: string;
            /** Id */
            id?: string;
            /** Llm Profile Id */
            llm_profile_id?: string | null;
            /** Modalities */
            modalities?: components["schemas"]["Modality"][];
            /** Name */
            name: string;
            /** @default L1 */
            privacy_level: components["schemas"]["PrivacyLevel"];
            /** @default local */
            scope: components["schemas"]["ProjectScope"];
            /** @default draft */
            status: components["schemas"]["ProjectStatus"];
            /** Target Metric */
            target_metric?: string | null;
            task?: components["schemas"]["TaskType"] | null;
            /**
             * Template
             * @description Plantilla UC-xx de origen
             */
            template?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Version
             * @description Versión para bloqueo optimista
             * @default 1
             */
            version: number;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Goal
             * @default
             */
            goal: string;
            /** Modalities */
            modalities?: components["schemas"]["Modality"][];
            /** Name */
            name: string;
            /** @default L1 */
            privacy_level: components["schemas"]["PrivacyLevel"];
            /** Target Metric */
            target_metric?: string | null;
            task?: components["schemas"]["TaskType"] | null;
            /** Template */
            template?: string | null;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Description */
            description?: string | null;
            /** Goal */
            goal?: string | null;
            /** Modalities */
            modalities?: components["schemas"]["Modality"][] | null;
            /** Name */
            name?: string | null;
            privacy_level?: components["schemas"]["PrivacyLevel"] | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Target Metric */
            target_metric?: string | null;
            task?: components["schemas"]["TaskType"] | null;
            /**
             * Version
             * @description Versión conocida por el cliente (bloqueo optimista)
             */
            version: number;
        };
        /**
         * ProjectScope
         * @enum {string}
         */
        ProjectScope: "local" | "team";
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "draft" | "active" | "archived";
        /**
         * RuntimeMode
         * @description Dónde corre este Engine (SPEC §4.3).
         * @enum {string}
         */
        RuntimeMode: "desktop" | "server";
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "classification" | "regression" | "forecasting" | "anomaly_detection" | "object_detection" | "segmentation" | "ocr" | "sound_event_detection";
        /** TorchInfo */
        TorchInfo: {
            /** Installed */
            installed: boolean;
            /**
             * Variant
             * @description cpu | cuXYZ | rocmX.Y | xpu
             */
            variant?: string | null;
            /** Version */
            version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionInfo */
        VersionInfo: {
            mode: components["schemas"]["RuntimeMode"];
            /** Platform */
            platform: string;
            /** Python */
            python: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHardware: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareReport"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
